defaults:
  - data: rivals
  - features: rivals_default
  - train: base
  - preprocess: default
  - model: rf
  - search: rf_randomized_large
  - _self_

outdir: results/${data.name}_${model.name}
run_shap: false
save_model: true



